POST http://localhost:3000/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6InRlc3RlIHRlc3RlIiwiZW1haWwiOiJ0ZXN0ZUB0ZXN0ZS5jb20iLCJwYXNzd29yZCI6IiQyYiQwOCR4MU9CZVUzNnlwZ21ZTDRMV0p1aDN1VnRLQzlyNmQudkFpdjN2aDUwQnI2ZU42VmZ5RHUzYSIsImlhdCI6MTcwNjIxMjE1NiwiZXhwIjoxNzA2Mjk4NTU2fQ.T7PhxL-WR4M6t5zsT5RkuFoo774ERIzxQqXMaHJTlB8
Content-Type: application/json

{
  "name":"cliente teste dois",
  "email":"teste2@teste.com",
  "cpf":"08117921022"
}

###
PATCH http://localhost:3000/client/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6InRlc3RlIHRlc3RlIiwiZW1haWwiOiJ0ZXN0ZUB0ZXN0ZS5jb20iLCJwYXNzd29yZCI6IiQyYiQwOCR4MU9CZVUzNnlwZ21ZTDRMV0p1aDN1VnRLQzlyNmQudkFpdjN2aDUwQnI2ZU42VmZ5RHUzYSIsImlhdCI6MTcwNjIxMjE1NiwiZXhwIjoxNzA2Mjk4NTU2fQ.T7PhxL-WR4M6t5zsT5RkuFoo774ERIzxQqXMaHJTlB8
Content-Type: application/json

{
  "name":"cliente teste",
  "cpf": "83425626035"
}

###
DELETE http://localhost:3000/client/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6InRlc3RlIHRlc3RlIiwiZW1haWwiOiJ0ZXN0ZUB0ZXN0ZS5jb20iLCJwYXNzd29yZCI6IiQyYiQwOCR4MU9CZVUzNnlwZ21ZTDRMV0p1aDN1VnRLQzlyNmQudkFpdjN2aDUwQnI2ZU42VmZ5RHUzYSIsImlhdCI6MTcwNjIxMjE1NiwiZXhwIjoxNzA2Mjk4NTU2fQ.T7PhxL-WR4M6t5zsT5RkuFoo774ERIzxQqXMaHJTlB8

###
GET http://localhost:3000/client/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6InRlc3RlIHRlc3RlIiwiZW1haWwiOiJ0ZXN0ZUB0ZXN0ZS5jb20iLCJwYXNzd29yZCI6IiQyYiQwOCR4MU9CZVUzNnlwZ21ZTDRMV0p1aDN1VnRLQzlyNmQudkFpdjN2aDUwQnI2ZU42VmZ5RHUzYSIsImlhdCI6MTcwNjIxMjE1NiwiZXhwIjoxNzA2Mjk4NTU2fQ.T7PhxL-WR4M6t5zsT5RkuFoo774ERIzxQqXMaHJTlB8

###
GET http://localhost:3000/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6InRlc3RlIHRlc3RlIiwiZW1haWwiOiJ0ZXN0ZUB0ZXN0ZS5jb20iLCJwYXNzd29yZCI6IiQyYiQwOCR4MU9CZVUzNnlwZ21ZTDRMV0p1aDN1VnRLQzlyNmQudkFpdjN2aDUwQnI2ZU42VmZ5RHUzYSIsImlhdCI6MTcwNjIxMjE1NiwiZXhwIjoxNzA2Mjk4NTU2fQ.T7PhxL-WR4M6t5zsT5RkuFoo774ERIzxQqXMaHJTlB8